// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://lkigswimupddzbypddvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxraWdzd2ltdXBkZHpieXBkZHZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ4NjI3ODEsImV4cCI6MjA5MDQzODc4MX0.HgQf0HYePG9qAhhSR2UgOzgNXiPPm7eywZMuO_Mobis";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);